# -*- coding: utf-8 -*-
#!/usr/bin/env python3
#
# resume documentation build configuration file, created by
# sphinx-quickstart on Mon Jun 12 01:20:51 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = []

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'resume'
copyright = ''
author = ''

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = ''
# The full version, including alpha/beta/rc tags.
release = ''

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ja'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    'papersize': 'a4paper', # A4サイズ
    'tableofcontents': '',  # 目次非表示
    'maketitle': '',        # 表紙非表示
    'preamble': ur'''
% 余白 ------------
\geometry{left=15mm,right=15mm,top=15mm,bottom=10mm}

% 行間(文章) --------
\renewcommand{\baselinestretch}{0.8}

% 行間(表) ----------
\renewcommand{\arraystretch}{1.2}

% 行間(箇条書き) ----
\let\olditemize\itemize
\renewcommand{\itemize}{
  \olditemize
  \setlength{\itemsep}{0pt}
  \setlength{\parskip}{0pt}
  \setlength{\parsep}{0pt}
}
% 行間(番号リスト) ----
\let\oldenumerate\enumerate
\renewcommand{\enumerate}{
  \oldenumerate
  \setlength{\itemsep}{0pt}
  \setlength{\parskip}{0pt}
  \setlength{\parsep}{0pt}
}
% 行間(説明リスト) ----
\let\olddescription\description
\renewcommand{\description}{
  \olddescription
  \setlength{\itemsep}{0pt}
  \setlength{\parskip}{0pt}
  \setlength{\parsep}{0pt}
}

% section
\titleformat{\section}[block]
{}{}{0pt}
{
  \normalfont \Huge\bfseries
  \hspace{-0.35cm}
}
[
\begin{picture}(100,0)
  \put(0,30){\color{lightgray}\line(1,0){515}}
\end{picture}
\\
\vspace{-2.2cm}
]

% subsection
\titleformat{\subsection}[block]
{}{}{0pt}
{
  \normalfont \LARGE\bfseries
  \hspace{-0.26cm}
}
[
\begin{picture}(100,0)
  \put(0,25){\color{lightgray}\line(1,0){515}}
\end{picture}
\\
\vspace{-1.8cm}
]

% subsubsection の行間を詰める  ----
\makeatletter
  \renewcommand{\@seccntformat}[1]{}
  \renewcommand{\subsubsection}{%
    \@startsection{subsubsection}{1}{\z@}%
    {0.1\Cvs}{0.1\Cvs}%
    {\normalfont\large\headfont\raggedright}
  }
\makeatother
''',
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',

    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}
latex_docclass = {'howto':'jsarticle'}
latex_documents = [
    (master_doc, 'resume.tex', 'resume Documentation',
     'tell-k', 'howto'),
]
